### ISSUE TITLE
Add support to query ECOS device API through orchestrator /appliance/rest endpoint

### ISSUE THREAD

**Issue by cdwchriburg** [aruba/pyedgeconnect#3]
It would be very useful if the `EdgeConnect` class could be extended so that it authenticates through Orchestrator and pulls data through orchestrator via the `/appliance/rest/{nePk}/{url}` Orchestrator Endpoint.

This appears to be a reverse proxy into the device-level/ECOS API so that any of the API commands the `EdgeConnect` class can run directly, the same commands can be run by appending the API endpoint URL to this Orchestrator API endpoint.

This removes the need to try and route from the automation system to each individual appliance since some commands (such as adding static routes) require talking to the device API directly rather than to the Orchestrator API.

It looks like the URL passed to `EdgeConnect` class is not used directly, so doesn't seem like we could just hack on a `url="customer-orch-use1.silverpeak.cloud/gms/rest/appliance/rest/0.NE/"` value to the `EdgeConnect` class during instantiation to trick it into doing this in with the current code.

**Comment by zachcamara-hpe** [comment]
The endpoints in the Orchestrator class already exist for those passthrough GET/POST/DELETE functions.

The value here would be leverage the existing work of parameter setup/endpoint format from the EdgeConnect class functions rather than having to look them up from source code and/or swagger.

As you noted, while this idea could be achieved, it would take some dedicated time on implementing cross-compatible logic which right now can't be a priority. For right now I'm going to close this as not planned.
